CREATE TABLE [reporting].[FactK12StudentEnrollments]
	(
		[FactK12StudentEnrollmentId]        [bigint] IDENTITY (1,1),
		[CohortYear]                        [smallint],
		[SchoolYear]                        [smallint]   NOT NULL,
		[CohortGraduationYear]              [smallint],
		[ProjectedGraduationYear]           [smallint],
		[SeaId]                             [int]        NOT NULL,
		[LeaId]                             [int]        NOT NULL,
		[K12SchoolId]                       [int]        NOT NULL,
		[K12StudentId]                      [bigint]     NOT NULL,
		[GradeLevelCode]                    [varchar](8) NOT NULL,
		[RaceId]                            [int]        NULL,
		[EnglishLearnerStatusId]            [int]        NULL,
		[HomelessnessStatusId]              [int]        NULL,
		[EconomicallyDisadvantagedStatusId] [int]        NULL,
		[FosterCareStatusId]                [int]        NULL,
		[NOrDStatusId]                      [int]        NULL,
		[DisabilityStatusId]                [int]        NULL,
		[K12DemographicId]                  [int]        NULL,
		CONSTRAINT [PK_FactK12StudentEnrollmentId] PRIMARY KEY ([FactK12StudentEnrollmentId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_CohortYear_DimSchoolYears_Year] FOREIGN KEY ([CohortYear]) REFERENCES [reporting].[DimSchoolYears] ([Year]),
		CONSTRAINT [FK_FactK12StudentEnrollments_SchoolYear_DimSchoolYears_Year] FOREIGN KEY ([SchoolYear]) REFERENCES [reporting].[DimSchoolYears] ([Year]),
		CONSTRAINT [FK_FactK12StudentEnrollments_CohortGraduationYear_DimSchoolYears_Year] FOREIGN KEY ([CohortGraduationYear]) REFERENCES [reporting].[DimSchoolYears] ([Year]),
		CONSTRAINT [FK_FactK12StudentEnrollments_ProjectedGraduationYear_DimSchoolYears_Year] FOREIGN KEY ([ProjectedGraduationYear]) REFERENCES [reporting].[DimSchoolYears] ([Year]),
		CONSTRAINT [FK_FactK12StudentEnrollments_SeaId_DimSEAs_DimSeaId] FOREIGN KEY ([SeaId]) REFERENCES [reporting].[DimSEAs] ([DimSeaId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_LeaId_DimLEAs_DimLeaId] FOREIGN KEY ([LeaId]) REFERENCES [reporting].[DimLEAs] ([DimLeaId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_K12SchoolId_DimK12Schools_DimK12SchoolId] FOREIGN KEY ([K12SchoolId]) REFERENCES [reporting].[DimK12Schools] ([DimK12SchoolId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_K12StudentId_DimStudents_DimK12StudentId] FOREIGN KEY ([K12StudentId]) REFERENCES [reporting].[DimStudents] ([DimK12StudentId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_GradeLevelCode_DimGradeLevels_GradeLevelCode] FOREIGN KEY ([GradeLevelCode]) REFERENCES [reporting].[DimGradeLevels] ([GradeLevelCode]),
		CONSTRAINT [FK_FactK12StudentEnrollments_RaceId_DimAssessments_K12CourseStatusId] FOREIGN KEY ([RaceId]) REFERENCES [reporting].[DimRaces]([DimRaceId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_EnglishLearnerStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([EnglishLearnerStatusId]) REFERENCES [reporting].[DimEnglishLearnerStatuses]([DimEnglishLearnerStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_HomelessnessStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([HomelessnessStatusId]) REFERENCES [reporting].[DimHomelessnessStatuses]([DimHomelessnessStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_EconomicallyDisadvantagedStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([EconomicallyDisadvantagedStatusId]) REFERENCES [reporting].[DimEconomicallyDisadvantagedStatuses]([DimEconomicallyDisadvantagedStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_FosterCareStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([FosterCareStatusId]) REFERENCES [reporting].[DimFosterCareStatuses]([DimFosterCareStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_NOrDStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([NOrDStatusId]) REFERENCES [reporting].[DimNOrDStatuses]([DimNOrDStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_DisabilityStatusId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([DisabilityStatusId]) REFERENCES [reporting].[DimDisabilityStatuses]([DimDisabilityStatusId]),
		CONSTRAINT [FK_FactK12StudentEnrollments_K12DemographicId_DimAssessmentSubtests_K12CourseStatusId] FOREIGN KEY ([K12DemographicId]) REFERENCES [reporting].[DimK12Demographics]([DimK12DemographicId]),
		INDEX [NCIX_FactK12StudentEnrollments_NaturalKey] NONCLUSTERED
			([SchoolYear], [SeaId], [LeaId], [K12SchoolId], [K12StudentId], [GradeLevelCode])
	)
GO
--------------------------------------------------------------------------------------
